<?php

namespace Database\Seeders;

use App\Models\HakModels\Settings;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        // type - text checkbox select

        // hsbr_frontend settings
        Settings::create(['name' => 'hsbr_contact_email', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'info@hsbr.app', 'value' => 'info@hsbr.app', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_contact_address', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '105 Whitlock Ave, Canada', 'value' => '105 Whitlock Ave, Canada', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_contact_phone', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '+91 9946 56 4387', 'value' => '+91 9946 56 4387', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_contact_map', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://google/maps/7z3vz5Z    ', 'value' => 'https://goo.gl/maps/7z3vz5Z    ', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        Settings::create(['name' => 'hsbr_satisfied_customers_count', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '45', 'value' => '45', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);


        Settings::create(['name' => 'hsbr_twitter_link', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://x.com/home', 'value' => 'https://x.com/home', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_facebook_link', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://www.facebook.com/', 'value' => 'https://www.facebook.com/', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_pinterest_link', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://www.pinterest.com/', 'value' => 'https://www.pinterest.com/', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_instagram_link', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://www.instagram.com/', 'value' => 'https://www.instagram.com/', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_youtube_link', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://www.youtube.com/', 'value' => 'https://www.youtube.com/', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_whatsapp_link', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => 'https://www.whatsapp.com/', 'value' => 'https://www.whatsapp.com/', 'type' => 'admin', 'group' => 'application', 'parent' => 'home', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        Settings::create(['name' => 'hsbr_frontend_layout_dark_mode', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        Settings::create(['name' => 'hsbr_frontend_layout_main_slider', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_services', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_trust', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_about', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_video', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_feature', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_faq', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_team', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_why_choose', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_projects', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_testimonial', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_brand_partners', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_contact_us', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_blog', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hsbr_frontend_layout_contact_now', 'model' => 'hsbrFrontend', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'hsbrAdmin', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);






        // production settings
        Settings::create(['name' => 'app_name', 'model' => 'app', 'data' => '', 'default_value' => 'HSBR-Apps', 'value' => 'HSBR-Apps', 'type' => 'production', 'group' => 'application', 'parent' => 'application', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'app_version', 'model' => 'app', 'data' => '', 'default_value' => '1.01', 'value' => '1.01', 'type' => 'production', 'group' => 'application', 'parent' => 'page', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'hak_version', 'model' => 'app', 'data' => '', 'default_value' => '1.01', 'value' => '1.01', 'type' => 'production', 'group' => 'application', 'parent' => 'page', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'page_title_prefix', 'model' => 'app', 'data' => '', 'default_value' => 'HSBR', 'value' => 'HSBR', 'type' => 'production', 'group' => 'application', 'parent' => 'page', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'page_title_suffix', 'model' => 'app', 'data' => '', 'default_value' => 'online', 'value' => 'Online', 'type' => 'production', 'group' => 'application', 'parent' => 'page', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'page_title_description', 'model' => 'app', 'data' => '', 'default_value' => 'default description', 'value' => 'default description', 'type' => 'production', 'group' => 'application', 'parent' => 'page', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'page_title_message', 'model' => 'app', 'data' => '', 'default_value' => 'default message', 'value' => 'default message', 'type' => 'production', 'group' => 'application', 'parent' => 'page', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'developer_company_name', 'model' => 'app', 'data' => '', 'default_value' => 'HSBR-Apps', 'value' => 'HSBR-Apps', 'type' => 'production', 'group' => 'developer', 'parent' => 'developer_company', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'developer_company_website', 'model' => 'app', 'data' => '', 'default_value' => 'https://hsbr.app', 'value' => 'https://hsbr.app', 'type' => 'production', 'group' => 'developer', 'parent' => 'developer_company', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'developer_company_mail', 'model' => 'app', 'data' => '', 'default_value' => 'hisham@hsbr.app', 'value' => 'hisham@hsbr.app', 'type' => 'production', 'group' => 'developer', 'parent' => 'developer_company', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'developer_app_starting_year', 'model' => 'app', 'data' => '', 'default_value' => '2020', 'value' => '2020', 'type' => 'production', 'group' => 'developer', 'parent' => 'developer_company', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        // admin settings
        Settings::create(['name' => 'logo_sidebar', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'logo', 'parent' => 'logo_sidebar', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'logo_sidebar_mini', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'logo', 'parent' => 'logo_sidebar', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'logo_sign', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'logo', 'parent' => 'logo_sign', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'logo_sign_mini', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'logo', 'parent' => 'logo_sign', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'logo_sign_with_google', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'logo', 'parent' => 'logo_sign', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'logo_sign_with_facebook', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'logo', 'parent' => 'logo_sign', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'layout_sidebar_collapse', 'model' => 'app', 'data' => '', 'default_value' => 'null', 'value' => '1', 'type' => 'admin', 'group' => 'layout', 'parent' => 'default', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'layout_dark_mode', 'model' => 'app', 'data' => '', 'default_value' => 'null', 'value' => '1', 'type' => 'admin', 'group' => 'layout', 'parent' => 'default', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'default_status', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'default', 'parent' => 'default_value', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Always Active"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'default_time_zone', 'model' => 'app', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'default', 'parent' => 'default_value', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Allow"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'permission_view', 'model' => 'app', 'data' => '', 'default_value' => 'list', 'value' => 'list', 'type' => 'admin', 'group' => 'default', 'parent' => 'default_value', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'select', 'form_data' => ["list", "group"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'edit_days', 'model' => 'app', 'data' => '', 'default_value' => '7', 'value' => '7', 'type' => 'admin', 'group' => 'default', 'parent' => 'default_value', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'delete_days', 'model' => 'app', 'data' => '', 'default_value' => '7', 'value' => '7', 'type' => 'admin', 'group' => 'default', 'parent' => 'default_value', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        // test demo model settings
        Settings::create(attributes: ['name' => 'test_demo_pdf_paper_size', 'model' => 'TestDemo', 'data' => '', 'default_value' => 'a4', 'value' => 'a4', 'type' => 'admin', 'group' => 'model', 'parent' => 'test_demo', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);


        Settings::create(attributes: ['name' => 'test_demo_view', 'model' => 'TestDemo', 'data' => '', 'default_value' => 'plain', 'value' => 'plain', 'type' => 'admin', 'group' => 'model', 'parent' => 'test_demo', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'test_demo_icon', 'model' => 'TestDemo', 'data' => '', 'default_value' => 'fa-user', 'value' => 'fa-user', 'type' => 'admin', 'group' => 'model', 'parent' => 'test_demo', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'test_demo_color', 'model' => 'TestDemo', 'data' => '', 'default_value' => 'yellow', 'value' => 'yellow', 'type' => 'admin', 'group' => 'model', 'parent' => 'test_demo', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        // user model settings
        Settings::create(['name' => 'user_icon', 'model' => 'user', 'data' => '', 'default_value' => 'fa-user', 'value' => 'fa-user', 'type' => 'admin', 'group' => 'model', 'parent' => 'user', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'user_color', 'model' => 'user', 'data' => '', 'default_value' => 'yellow', 'value' => 'yellow', 'type' => 'admin', 'group' => 'model', 'parent' => 'user', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        // dashboard settings
        Settings::create(['name' => 'dashboard_data_refresh', 'model' => 'dashboard', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'dashboard', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'dashboard_data_refresh_interval', 'model' => 'dashboard', 'data' => '', 'default_value' => '30000', 'value' => '30000', 'type' => 'admin', 'group' => 'application', 'parent' => 'dashboard', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'text', 'form_data' => '', 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);

        // backup settings
        Settings::create(['name' => 'backup_automatic_schedule', 'model' => 'backup', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'backup', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'backup_automatic_db_only', 'model' => 'backup', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'backup', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'backup_manual_schedule', 'model' => 'backup', 'data' => '', 'default_value' => '1', 'value' => '1', 'type' => 'admin', 'group' => 'application', 'parent' => 'backup', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'checkbox', 'form_data' => ["Enable"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
        Settings::create(['name' => 'backup_schedule_frequencies', 'model' => 'backup', 'data' => '', 'default_value' => "daily('00:00')", 'value' => "daily('00:00')", 'type' => 'admin', 'group' => 'application', 'parent' => 'backup', 'permission' => 'Admin Permit', 'default_by' => '1', 'form_type' => 'select', 'form_data' => ["everyTwoMinutes()", "hourly()", "daily()", "daily('00:00')", "weeklyOn(1, '00:00')", "monthly()", "lastDayOfMonth()"], 'description' => 'des', 'status' => '1', 'created_by' => '1', 'updated_by' => '1']);
    }
}
